### ISSUE TITLE
Le lien nous rejoindre est en 404

### ISSUE THREAD

**Issue by jsmadja** [xebia-studio/visMaVie-v2#6]
http://xebia-vis-ma-vie--master.s3-website.eu-central-1.amazonaws.com/nous-rejoindre

> 404 Not Found
> Code: NoSuchKey
> Message: The specified key does not exist.
> Key: nous-rejoindre
> RequestId: BC89E539A8D8B39A
> HostId: +1pNxUbMzROAaVunDuHKPzhK36zfBxcmFOekAPCfJheyCNPjFnL3zLiK6ZBPxDASc5elDcYs69g=

**Comment by ikempf** [comment]
Je pense que cela s'applique a toutes les pages, il suffit de recharger (F5) la page.

**Comment by keabard** [comment]
Oui, c'est dû au fait que le déploiement est effectué sur S3, et qu'il n'y a pas de router back. Une solution est en cours de mise en place pour palier à ce problème.

Merci !
